function [TRAINTARGET, TESTTARGET] = splitInTwo(TRAINCLASSES,TESTCLASSES, deciderFn)

TRAINTARGET = ones(size(TRAINCLASSES));
TRAINTARGET(~deciderFn(TRAINCLASSES)) = -1;

TESTTARGET = ones(size(TESTCLASSES));
TESTTARGET(~deciderFn(TESTCLASSES)) = -1;

end