function [TRAINTARGET, TESTTARGET] = splitInTwo(TRAINCLASSES,TESTCLASSES, deciderFn)

TRAINTARGET = zeros(size(TRAINCLASSES));
TRAINTARGET(deciderFn(TRAINCLASSES)) = 1;
TRAINTARGET(~deciderFn(TRAINCLASSES)) = -1;

TESTTARGET = zeros(size(TESTCLASSES));
TESTTARGET(deciderFn(TESTCLASSES)) = 1;
TESTTARGET(~deciderFn(TESTCLASSES)) = -1;

end