dispstat(sprintf('\n\n\n%s',repmat('#',1,30)),'keepprev','keepthis');
dispstat('STROKES','keepprev');

load('data/strokefeatures.mat');

[TEST TESTCLASS TRAIN TRAINCLASS] = splitDataIntoTestAndTraining( ...
    features_class(:,1:20), ...
    features_class(:,21), ...
    0.8, ...
    1 ...
);

clearvars features_class;